import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TRPCReactProvider } from "@/trpc/react";
import { MainNavigation } from "@/components/MainNavigation";
import CookieBanner from "@/components/CookieBanner";

export const metadata: Metadata = {
  title: "Datenschutz Training",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="de" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <MainNavigation />
          {children}
          <CookieBanner />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
